[package]
name = "keithley-2230-series"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
visa-api = "0.1.1"
thiserror = "1.0.50"